### PR TITLE
Align protoc versions with protobuf

### LINKED ISSUE #1238: protoc doesn't support Apple silicon/M1
### Short description

Protobuf's `protoc` is not published pre-compiled for Apple Silicon/M1 https://github.com/protocolbuffers/protobuf/issues/8062

```
protoc-jar: protoc version: 3.11.4, detected platform: osx-aarch_64 (mac os x/aarch64)
...
[error] stack trace is suppressed; run last Compile / protocGenerate for the full output
[error] (Compile / protocGenerate) error occurred while compiling protobuf files: Unsupported platform: protoc-3.11.4-osx-aarch_64.exe
```

ScalaPB instructs users to compile it locally https://github.com/scalapb/ScalaPB/issues/1024

### PR DESCRIPTION
**Pull request by johanandren**
Instead of transitively getting the version selected by ScalaPB (and hardcoded string in Maven plugin)

Indirectly fixes #1238

### CODE REVIEW

File: project/Dependencies.scala [hunk 1]
```diff
@@ -78,6 +80,7 @@ object Dependencies {
   }
 
   object Protobuf {
+    val protobufJava = "com.google.protobuf" % "protobuf-java" % Versions.googleProtobuf
```
Comment (johanandren) [inline project/Dependencies.scala:83]: So scalapb-runtime actually pulls in the older protobuf-java artifact with generated classes as well as protoc, if that doesn't match up with the protoc version things fail.

File: build.sbt [hunk 2]
```diff
@@ -55,7 +55,9 @@ lazy val runtime = Project(id = akkaGrpcRuntimeName, base = file("runtime"))
       previousStableVersion.value.map(v => Set(organization.value %% "akka-grpc-runtime" % v)).getOrElse(Set.empty),
     AutomaticModuleName.settings("akka.grpc.runtime"),
     ReflectiveCodeGen.generatedLanguages := Seq("Scala"),
-    ReflectiveCodeGen.extraGenerators := Seq("ScalaMarshallersCodeGenerator"))
+    ReflectiveCodeGen.extraGenerators := Seq("ScalaMarshallersCodeGenerator"),
+    PB.protocVersion := Dependencies.Versions.googleProtobuf
```
Comment (johanandren) [inline build.sbt:59]: These two modules use scalapb directly so need the version explicitly added.

File: maven-plugin/src/main/maven/plugin.xml [hunk 3]
```diff
@@ -94,7 +94,8 @@
         <extraGenerators implementation="java.util.List" default-value=""/>
         <protoPaths default-value="${project.basedir}/src/main/proto,${project.basedir}/src/main/protobuf">${akka-grpc.protoPaths}</protoPaths>
         <outputDirectory default-value="${project.build.directory}/generated-sources">${akka-grpc.outputDirectory}</outputDirectory>
-        <protocVersion implementation="java.lang.String" default-value="-v3.11.4">${akka-grpc.protoc-version}</protocVersion>
+        <!-- Keep aligned with Akka gRPC proto-java dependency -->
+        <protocVersion implementation="java.lang.String" default-value="-v3.18.1">${akka-grpc.protoc-version}</protocVersion>
```
Comment (johanandren) [inline maven-plugin/src/main/maven/plugin.xml:98]: Couldn't quite figure out if this is picked up from elsewhere somehow or the default is actually used

**Comment by johanandren** [comment]
Verified that a snapshot of this pr works for both the sbt plugin and the maven plugin on my m1

File: sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala [hunk 4]
```diff
@@ -99,7 +99,9 @@ object AkkaGrpcPlugin extends AutoPlugin {
         // hack to get our (dirty) hands on a proper sbt logger before running the generators
         generatorLogger.logger = streams.value.log
         (Test / PB.recompile).value
-      })
+      },
+      // Keep aligned with Akka gRPC proto-java dependency
+      PB.protocVersion := "3.18.1")
```
Comment (raboof) [inline sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala:104]:
```suggestion
      PB.protocVersion := akka.grpc.gen.BuildInfo.googleProtobufVersion)
```

**Review by raboof — APPROVED** [review]

**Review by raboof — APPROVED** [review]
